name: "publish"

on:
  push:
    branches:
      - release
jobs:
  publish-tauri:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Setup Java (For building android apps)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # Setup Android SDK (For building android app)
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Install Android NDK (Required to build native deps)
      - name: Install NDK
        run: sdkmanager "ndk;27.0.11902837"

      # Setup the signing settings
      - name: setup Android signing
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      # Setup node to build frontend
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install rust with the various android targets
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      # Required to generate license metadata
      - name: install cargo-license
        run: cargo install cargo-license

      # These deps have some platform specific components which causes CI to fail due to
      # the package-lock.json having different locked platform specific installs
      - name: install problematic dependencies
        run: npm install --save-dev @tauri-apps/cli

      # Install frontend dependencies
      - name: Install dependencies
        run: npm install

      - name: generate THIRD_PARTY_LICENSES.md
        run: npm run make:licenses

      - name: Build app bundle
        run: npm run tauri android build
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/27.0.11902837

      - name: Get App Version
        id: app_version
        run: |
          APP_VERSION=$(node -p "require('./src-tauri/tauri.conf.json').version")
          echo "version=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Move build files
        run: |
          mv ./src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk ./tilepad-${{ steps.app_version.outputs.version }}.apk
          mv ./src-tauri/gen/android/app/build/outputs/bundle/universalRelease/app-universal-release.aab ./tilepad-${{ steps.app_version.outputs.version }}.aab

      - name: Create latest.json
        run: |
          echo "{ \"version\": \"${{ steps.app_version.outputs.version }}\" }" > latest.json

      - name: Publish
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.app_version.outputs.version }}
          name: App v${{ steps.app_version.outputs.version }}
          draft: true
          generate_release_notes: true
          files: |
            ./tilepad-${{ steps.app_version.outputs.version }}.apk
            ./tilepad-${{ steps.app_version.outputs.version }}.aab
            ./latest.json
